- name: Ensure allowedregistries Application directories exists
  file:
    path: "{{ openshift_gitops_dir}}/allowedregistries/{{ item }}"
    state: directory
  loop:
  - assets

- name: Create asset files
  template:
    src: "allowedregistries/{{ item.file }}.j2"
    dest: "{{ openshift_gitops_dir }}/allowedregistries/assets/{{ item.file }}"
  loop:
  - file: allowedregistries.yaml
  - file: external-registry-ca.yaml
  - file: gitops-rolebinding.yaml
  - file: sample-registries.yaml

- name: Find all generated files
  find:
    path: "{{ openshift_gitops_dir }}/allowedregistries/assets"
    file_type: file
  register: allowedregistries_asset_files

- name: Configure kustomization file
  template:
    src: allowedregistries/kustomization.yaml.j2
    dest: "{{ openshift_gitops_dir }}/allowedregistries/kustomization.yaml"
