---
- name: Ensure allowedregistries Application directories exists
  loop:
    - assets
  ansible.builtin.file:
    path: "{{ openshift_gitops_dir}}/allowedregistries/{{ item }}"
    state: directory

- name: Create asset files
  loop:
    - file: allowedregistries.yaml
    - file: external-registry-ca.yaml
    - file: gitops-rolebinding.yaml
    - file: sample-registries.yaml
  ansible.builtin.template:
    src: allowedregistries/{{ item.file }}.j2
    dest: "{{ openshift_gitops_dir }}/allowedregistries/assets/{{ item.file }}"

- name: Find all generated files
  register: allowedregistries_asset_files
  ansible.builtin.find:
    path: "{{ openshift_gitops_dir }}/allowedregistries/assets"
    file_type: file

- name: Configure kustomization file
  ansible.builtin.template:
    src: allowedregistries/kustomization.yaml.j2
    dest: "{{ openshift_gitops_dir }}/allowedregistries/kustomization.yaml"
