---
- name: Ensure gitops directories exist
  vars:
    gitops_component: cicd-operators
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Get components to install
  ansible.builtin.set_fact:
    cicd_components:
      - "{{ cicd_operators_install_tekton | default(True) | ternary('cicd-operators/tekton', '') }}"
      - "{{ cicd_operators_install_knative | default(True) | ternary('cicd-operators/knative', '') }}"

- name: Generate kustomization file
  vars:
    gitops_component: cicd-operators
    gitops_component_has_upstream: false
    gitops_component_extra_base_components: "{{ cicd_components | select() | list }}"
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
