---
- name: Ensure gitops directories exist
  vars:
    gitops_component: compliance-operator
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Set custom Compliance Operator subscription channel
  when:
    - compliance_operator_channel is defined
  ansible.builtin.template:
    src: compliance_operator/subscription-patch.yml.j2
    dest: "{{ openshift_gitops_dir }}/compliance-operator/patches/subscription-channel.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: compliance-operator
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
