---
- name: Ensure gitops directories exist
  vars:
    gitops_component: console
    extra_dirs:
      - files
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Create Custom Logo File
  when:
    - custom_logo_file is defined
    - "'branding' in openshift_components"
  ansible.builtin.copy:
    dest: "{{ openshift_gitops_dir }}/console/files/custom-logo.svg"
    content: |
      {{ lookup('file', custom_logo_file) | indent(width=2) }}

- name: Create Console patch for custom logo
  when:
    - custom_logo_file is defined or custom_product_name is defined
    - "'branding' in openshift_components"
  ansible.builtin.template:
    src: console/console-logo-patch.yml.j2
    dest: "{{ openshift_gitops_dir }}/console/patches/console-logo.yaml"

- name: Set custom console url
  when:
    - custom_console_url is defined
  ansible.builtin.template:
    src: console/custom_console_url.yml.j2
    dest: "{{ openshift_gitops_dir }}/console/patches/custom_console_url.yaml"

- name: create ConfigMapGenerator for branding files
  when:
    - custom_logo_file is defined
    - "'branding' in openshift_components"
  ansible.builtin.set_fact:
    console_extra_content:
      - configMapGenerator:
          - name: custom-logo
            namespace: openshift-config
            options:
              disableNameSuffixHash: true
              annotations:
                argocd.argoproj.io/sync-options: Replace=true
                argocd.argoproj.io/compare-options: IgnoreExtraneous
            files:
              - files/custom-logo.svg

- name: Generate kustomization file
  vars:
    gitops_component: console
    gitops_component_extra_content: "{{ console_extra_content | default([]) }}"
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
