---
- name: Encrypt secret
  register: secret_sealed_raw
  ansible.builtin.command:
    cmd: "{{ kubeseal_command }} --cert={{ kubeseal_cert }}"
    stdin: "{{ secret_template | to_json }}"

- name: Create sealed secret object
  when:
    - apply_to_cluster | default(false) == true
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ secret_sealed_raw.stdout | from_json }}"

- name: Create sealed secret file
  when:
    - sealed_secret_file is defined
  ansible.builtin.copy:
    dest: "{{ sealed_secret_file }}"
    content: "{{ secret_sealed_raw.stdout | from_json | to_nice_yaml }}"
