---
- name: Get SSH privkey for repo
  register: openshift_gitops_repo_ssh_privkey_content
  when:
    - openshift_gitops_repo_ssh_privkey_file is defined
  ansible.builtin.slurp:
    src: "{{ openshift_gitops_repo_ssh_privkey_file }}"

- name: Create sealed secret for repo
  vars:
    secret_template: "{{ lookup('template', 'create_applicationset/repo.yml.j2') | from_yaml }}"
    apply_to_cluster: true
  ansible.builtin.include_tasks: create_sealed_secret.yml

- name: Wait for Repo secret to appear
  register: wait_for_repo_secret
  until:
    - wait_for_repo_secret.resources is defined
    - ( wait_for_repo_secret.resources | length ) > 0
  retries: 100
  kubernetes.core.k8s_info:
    kubeconfig: "{{ openshift_kubeconfig }}"
    api_version: v1
    kind: Secret
    name: "{{ openshift_gitops_repo_name | default('gitops') }}-repo"
    namespace: openshift-gitops

- name: Create cluster-config ApplicationSet
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'create_applicationset/applicationset.yml.j2') | from_yaml }}"
