---
- name: Ensure git assets  and patches directory exist
  loop: "{{ ['assets', 'patches'] + (extra_dirs | default([])) }}"
  ansible.builtin.file:
    path: "{{ openshift_gitops_dir }}/{{ gitops_component }}/{{ item }}"
    state: directory
