---
- name: Encrypt secret
  command:
    cmd: "{{ kubeseal_command }} --cert={{ kubeseal_cert }}"
    stdin: "{{ secret_template | to_json }}"
  register: secret_sealed_raw

- name: Create sealed secret object
  k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ secret_sealed_raw.stdout | from_json }}"
  when:
  - apply_to_cluster | default(false) == true

- name: Create sealed secret file
  copy:
    dest: "{{ sealed_secret_file }}"
    content: "{{ secret_sealed_raw.stdout | from_json | to_nice_yaml }}"
  when:
  - sealed_secret_file is defined
