---
- name: Find all generated files
  register: gitops_component_files
  ansible.builtin.find:
    path: "{{ openshift_gitops_dir }}/{{ gitops_component }}/assets"
    file_type: file

- name: Find all generated patches
  register: gitops_component_patches_strategic
  ansible.builtin.find:
    path: "{{ openshift_gitops_dir }}/{{ gitops_component }}/patches"
    file_type: file

- name: Configure kustomization file
  ansible.builtin.template:
    src: common/kustomization.yaml.j2
    dest: "{{ openshift_gitops_dir }}/{{ gitops_component }}/kustomization.yaml"
