---
- name: Slurp ca content
  register: groupsync_ca_content
  ansible.builtin.slurp:
    src: "{{ item.cafile }}"

- name: Configure oauth bind passwords sealed-secret
  vars:
    secret_template: "{{ lookup('template', 'groupsync/groupsync-ca.yml.j2') | from_yaml }}"
    apply_to_cluster: false
    sealed_secret_file: "{{ openshift_gitops_dir }}/groupsync/assets/groupsync-ca-{{ item.name }}.yaml"
  when:
    - item.type | default('LDAP') == 'LDAP'
  ansible.builtin.include_tasks: create_sealed_secret.yml
