---
- name: Slurp kubeconfig file
  slurp:
    src: "{{ openshift_kubeconfig }}"
  register: kubeconfig_raw

- name: Read file
  set_fact:
    kubeconfig_content: "{{ kubeconfig_raw.content | b64decode | from_yaml }}"

- name: Extract cabundle
  set_fact:
    cabundlestring: "{{ kubeconfig_content.clusters[0]['cluster']['certificate-authority-data'] | default('') }}"
    cabundle: "{{ kubeconfig_content.clusters[0]['cluster']['certificate-authority-data'] | default('') | b64decode | regex_findall('(?ms)^-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----$', multiline=True) }}"

- name: Slurp extra certs
  slurp:
    src: "{{ custom_ca_file }}"
  register: custom_ca_content_raw

- name: Read extra certs
  set_fact:
    new_cacerts: "{{ custom_ca_content_raw.content | b64decode }}"

- name: Extract new cabundle
  set_fact:
    newcabundle: "{{ new_cacerts | regex_findall('(?ms)^-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----$', multiline=True) }}"

- name: Create combined cabundle
  set_fact:
    combined: "{{ cabundle | union(newcabundle) | unique }}"

- name: Update kubeconfig variable
  set_fact:
     newkubeconfig_content: "{{ kubeconfig_content | regex_replace(cabundlestring, combined | join('\n') | b64encode ) }}"
  when:
  - cabundlestring | length > 0

- name: Write new kubeconfig
  copy:
    dest: "{{ openshift_kubeconfig }}"
    content: "{{ newkubeconfig_content | to_nice_yaml(indent=2) }}"
  when:
  - cabundlestring | length > 0

- name: Warn about modified kubeconfig
  debug:
    msg: |
      We could not find a "certificate-authority-data" configuration for the
      first cluster in {{ openshift_kubeconfig }} on {{ bastion_host }}.
      As a result we have not updated anything. Fix your {{ openshift_kubeconfig }}
      file and run this task again (`--tags=kubeconfig_rootca`)

      In the future, please refrain from any `login` actions using the
      generated `system:admin` kubeconfig
  when:
  - not cabundlestring

- name: debug
  debug:
    msg: |
      Old cabundle had {{ cabundle | length }} entries
      Trying to add {{ newcabundle | length }} entries
      New cabundle has {{ combined | length }} entries
  when:
  - cabundlestring | length > 0

