---
- name: Ensure gitops directories exist
  vars:
    gitops_component: local-storage
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Find all defined host storage
  ansible.builtin.set_fact:
    local_storage_all_nodes: "{{ groups['masters'] + groups['infra'] + ( groups['storage']| default([]) ) + groups['workers'] | unique }}"

- name: Create LocalVolumes
  loop: "{{ local_storage_all_nodes }}"
  when: hostvars[item]['local_storage'] is defined
  ansible.builtin.template:
    src: local_storage/local-storage-operator-local-volume.yml.j2
    dest: "{{ openshift_gitops_dir }}/local-storage/assets/local-volumes-{{ item }}.yaml"

- name: Create nodeselector patch
  when:
    - groups['infra'] | default([])| length > 0
  ansible.builtin.template:
    src: local_storage/nodeselector.yaml.j2
    dest: "{{ openshift_gitops_dir }}/local-storage/patches/nodeselector.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: local-storage
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
