---
- name: Ensure gitops directories exist
  vars:
    gitops_component: logging
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Generate logging Config ConfigMap
  ansible.builtin.template:
    src: logging/cluster-logging.yml.j2
    dest: "{{ openshift_gitops_dir }}/logging/assets/cluster-logging.yaml"

- name: Generate nodeselector patches
  loop:
    - nodeselector-sub-es
    - nodeselector-sub-cl
  when:
    - groups['infra'] | default([]) | length > 0
  ansible.builtin.template:
    src: logging/{{ item }}.yaml.j2
    dest: "{{ openshift_gitops_dir }}/logging/patches/{{ item }}.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: logging
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
