- name: Configure Logging Using Loki
  include_tasks:
    file: logging-loki.yml
  when:
  - logging_type | default('elastic') == 'loki'

- name: Configure Logging Using Loki
  include_tasks:
    file: logging-elastic.yml
  when:
  - logging_type | default('elastic') == 'elastic'
