---
- name: Configure Logging Using Loki
  when:
    - logging_type | default('elastic') == 'loki'
  ansible.builtin.include_tasks:
    file: logging-loki.yml

- name: Configure Logging Using Loki
  when:
    - logging_type | default('elastic') == 'elastic'
  ansible.builtin.include_tasks:
    file: logging-elastic.yml
