---
- name: Ensure gitops directories exist
  vars:
    gitops_component: machineconfigs
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Add chrony machineConfigs
  loop:
    - master
    - worker
  loop_control:
    loop_var: chrony_role
  ansible.builtin.template:
    src: machineconfigs/99-chrony-machineconfig.yml.j2
    dest: "{{ openshift_gitops_dir }}/machineconfigs/assets/99-{{ chrony_role }}-chrony-configuration.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: machineconfigs
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
