---
- name: preflight
  include_tasks:
    file: preflight.yml
    apply:
      tags:
      - preflight
  tags:
  - preflight

- name: deploy_gitops
  include_tasks:
    file: deploy_gitops.yml
    apply:
      tags:
      - deploy_gitops
  when: "'deploy_gitops' in openshift_components"
  tags:
  - deploy_gitops

- name: sealed_secrets
  include_tasks:
    file: sealed_secrets.yml
    apply:
      tags:
      - sealed_secrets
  when: "'sealed_secrets' in openshift_components"
  tags:
  - sealed_secrets

- name: setup_git
  include_tasks:
    file: setup_git.yml
    apply:
      tags:
      - setup_git
  when: "'setup_git' in openshift_components"
  tags:
  - setup_git

- name: create_applicationset
  include_tasks:
    file: create_applicationset.yml
    apply:
      tags:
      - create_applicationset
  when: "'create_applicationset' in openshift_components"
  tags:
  - create_applicationset

- name: apiserver
  include_tasks:
    file: apiserver.yml
    apply:
      tags:
      - apiserver
  when: "'apiserver' in openshift_components"
  tags:
  - apiserver

- name: ingress
  include_tasks:
    file: ingress.yml
    apply:
      tags:
      - ingress
  when: "'ingress' in openshift_components"
  tags:
  - ingress

- name: network-policies
  include_tasks:
    file: network-policies.yml
    apply:
      tags:
      - network-policies
  when: "'network-policies' in openshift_components"
  tags:
  - network-policies

- name: oauth
  include_tasks:
    file: oauth.yml
    apply:
      tags:
      - oauth
  when: "'oauth' in openshift_components"
  tags:
  - oauth

- name: machineconfigs
  include_tasks:
    file: machineconfigs.yml
    apply:
      tags:
      - machineconfigs
  when: "'machineconfigs' in openshift_components"
  tags:
  - machineconfigs

- name: groupsync
  include_tasks:
    file: groupsync.yml
    apply:
      tags:
      - groupsync
  when: "'groupsync' in openshift_components"
  tags:
  - groupsync

- name: local_storage
  include_tasks:
    file: local_storage.yml
    apply:
      tags:
      - local_storage
  when: "'local_storage' in openshift_components"
  tags:
  - local_storage

- name: odf_storage
  include_tasks:
    file: odf_storage.yml
    apply:
      tags:
      - odf_storage
  when: "'odf_storage' in openshift_components"
  tags:
  - odf_storage

- name: console
  include_tasks:
    file: console.yml
    apply:
      tags:
      - console
  when: "'console' in openshift_components"
  tags:
  - console

- name: cicd-operators
  include_tasks:
    file: cicd-operators.yml
    apply:
      tags:
      - cicd-operators
  when: "'cicd-operators' in openshift_components"
  tags:
  - cicd-operators

- name: registry
  include_tasks:
    file: registry.yml
    apply:
      tags:
      - registry
  when: "'registry' in openshift_components"
  tags:
  - registry

- name: allowedregistries
  include_tasks:
    file: allowedregistries.yml
    apply:
      tags:
      - allowedregistries
  when: "'allowedregistries' in openshift_components"
  tags:
  - allowedregistries

- name: monitoring
  include_tasks:
    file: monitoring.yml
    apply:
      tags:
      - monitoring
  when: "'monitoring' in openshift_components"
  tags:
  - monitoring

- name: nfs-subdir-provisioner
  include_tasks:
    file: nfs-subdir-provisioner.yml
    apply:
      tags:
      - nfs-subdir-provisioner
  when: "'nfs-subdir-provisioner' in openshift_components"
  tags:
  - nfs-subdir-provisioner

- name: logging
  include_tasks:
    file: logging.yml
    apply:
      tags:
      - logging
  when: "'logging' in openshift_components"
  tags:
  - logging

- name: trident
  include_tasks:
    file: trident.yml
    apply:
      tags:
      - trident
  when: "'trident' in openshift_components"
  tags:
  - trident

- name: servicemesh
  include_tasks:
    file: servicemesh.yml
    apply:
      tags:
      - servicemesh
  when: "'servicemesh' in openshift_components"
  tags:
  - servicemesh

- name: metallb
  include_tasks:
    file: metallb.yml
    apply:
      tags:
      - metallb
  when: "'metallb' in openshift_components"
  tags:
  - metallb

- name: nodemaintenanceoperator
  include_tasks:
    file: nodemaintenanceoperator.yml
    apply:
      tags:
      - nodemaintenanceoperator
  when: "'nodemaintenanceoperator' in openshift_components"
  tags:
  - nodemaintenanceoperator

- name: compliance_operator
  include_tasks:
    file: compliance_operator.yml
    apply:
      tags:
      - compliance_operator
  when: "'compliance_operator' in openshift_components"
  tags:
  - compliance_operator

- name: cis_compliance
  include_tasks:
    file: cis_compliance.yml
    apply:
      tags:
      - cis_compliance
  when: "'cis_compliance' in openshift_components"
  tags:
  - cis_compliance

- name: proxy
  include_tasks:
    file: proxy.yml
    apply:
      tags:
      - proxy
  when: "'proxy' in openshift_components"
  tags:
  - proxy

- name: Update system:admin kubeconfig trusted CA
  include_tasks:
    file: kubeconfig_rootca.yml
    apply:
      tags:
      - kubeconfig_rootca
  when:
  - custom_ca_file is defined
  tags:
  - kubeconfig_rootca
