---
- name: Ensure gitops directories exist
  vars:
    gitops_component: metallb
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Create IPAddressPools
  loop: "{{ metallb.addresspools }}"
  ansible.builtin.template:
    src: metallb/addresspool.yaml.j2
    dest: "{{ openshift_gitops_dir }}/metallb/assets/addresspool-{{ item.name }}.yaml"

- name: Create BGPPeers
  loop: "{{ metallb.peers }}"
  ansible.builtin.template:
    src: metallb/bgppeer.yaml.j2
    dest: "{{ openshift_gitops_dir }}/metallb/assets/bgppeer-{{ item.name }}.yaml"

- name: Create BGPAdverstisements
  loop: "{{ metallb.bgpadvertisements | default([]) }}"
  ansible.builtin.template:
    src: metallb/bgpadvertisement.yaml.j2
    dest: "{{ openshift_gitops_dir }}/metallb/assets/bgpadvertisement-{{ item.name }}.yaml"

- name: Create L2Adverstisements
  loop: "{{ metallb.l2advertisements | default([]) }}"
  ansible.builtin.template:
    src: metallb/l2advertisement.yaml.j2
    dest: "{{ openshift_gitops_dir }}/metallb/assets/l2advertisement-{{ item.name }}.yaml"

- name: Template extra LoadBalancer Service for default Ingress
  when:
    - metallb.add_default_ingress_service | default(false)
  ansible.builtin.template:
    src: metallb/router-metallb-default.yaml.j2
    dest: "{{ openshift_gitops_dir }}/metallb/assets/router-metallb-default.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: metallb
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
