---
- name: Ensure gitops directories exist
  vars:
    gitops_component: monitoring
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Generate cluster-monitoring Config ConfigMap
  ansible.builtin.template:
    src: monitoring/cluster-monitoring-config.yml.j2
    dest: "{{ openshift_gitops_dir }}/monitoring/assets/cluster-monitoring-config.yaml"

- name: Generate user-workload-monitoring Config ConfigMap
  when:
    - monitoring_user_workload_enabled
  ansible.builtin.template:
    src: monitoring/user-workload-monitoring-config.yml.j2
    dest: "{{ openshift_gitops_dir }}/monitoring/assets/user-workload-monitoring-config.yaml"

- name: Configure AlertManager
  when:
    - alertmanager_config is defined
  ansible.builtin.template:
    src: monitoring/alertmanager-main.yml.j2
    dest: "{{ openshift_gitops_dir }}/monitoring/assets/alertmanager-main.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: monitoring
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
