---
- name: Ensure gitops directories exist
  vars:
    gitops_component: network-policies
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Generate kustomization file
  vars:
    gitops_component: network-policies
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
