---
- name: Ensure gitops directories exist
  vars:
    gitops_component: nfs-subdir-provisioner
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Set namespace node-selector if infra nodes are present
  ansible.builtin.template:
    src: nfs-subdir-provisioner/namespace.yml.j2
    dest: "{{ openshift_gitops_dir }}/nfs-subdir-provisioner/patches/namespace.yaml"

- name: Template nfs-client-provisioner deployment patch
  ansible.builtin.template:
    src: nfs-subdir-provisioner/deployment.yaml.j2
    dest: "{{ openshift_gitops_dir }}/nfs-subdir-provisioner/patches/deployment.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: nfs-subdir-provisioner
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
