---
- name: Ensure gitops directories exist
  vars:
    gitops_component: nodemaintenanceoperator
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Set custom Node Maintenance subscription channel
  when:
    - nodemaintenanceoperator_channel is defined
  ansible.builtin.template:
    src: nodemaintenanceoperator/subscription-patch.yml.j2
    dest: "{{ openshift_gitops_dir }}/nodemaintenanceoperator/patches/subscription-channel.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: nodemaintenanceoperator
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
