---
- name: Slurp ca content
  register: oauths_ca_content
  ansible.builtin.slurp:
    src: "{{ item.cafile }}"

- name: Template CA ConfigMap for Identity Provider
  ansible.builtin.template:
    src: oauth/oauths-ca.yml.j2
    dest: "{{ openshift_gitops_dir}}/oauth/assets/ldap-ca-{{ item.name }}.yml"
