---
- name: Ensure gitops directories exist
  vars:
    gitops_component: odf-storage
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Create LocalVolumeSet for local-storage
  ansible.builtin.template:
    src: odf_storage/localvolumeset.yml.j2
    dest: "{{ openshift_gitops_dir }}/odf-storage/assets/localvolumeset.yaml"

- name: Create StorageSystem
  ansible.builtin.template:
    src: odf_storage/storagesystem.yml.j2
    dest: "{{ openshift_gitops_dir }}/odf-storage/assets/storagesystem.yaml"

- name: Create StorageCluster
  ansible.builtin.template:
    src: odf_storage/storagecluster.yml.j2
    dest: "{{ openshift_gitops_dir }}/odf-storage/assets/storagecluster.yaml"

- name: Set custom odf_storage version
  ansible.builtin.template:
    src: odf_storage/subscription-patch.yml.j2
    dest: "{{ openshift_gitops_dir }}/odf-storage/patches/subscription-channel.yaml"

- name: Set custom odf_storage version
  when:
    - groups['storage'] | default([]) | length > 0
  ansible.builtin.template:
    src: odf_storage/nodeselector-sub.yaml.j2
    dest: "{{ openshift_gitops_dir }}/odf-storage/patches/nodeselector-sub.yaml"

- name: Generate kustomization file
  vars:
    gitops_component: odf-storage
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
