---
- name: routercerts_verify
  vars:
    cert_hostname: "{{ certificate.hostname | default('*.apps.'+cluster+'.'+base_domain) }}"
  loop: "{{ routercerts_certificates }}"
  loop_control:
    loop_var: certificate
    label: certificate.name
  when:
    - "'ingress' in openshift_components"
    - openshift_ingress_controllers is defined
    - certificate.certfile is defined
    - certificate.keyfile is defined
  tags:
    - ingress
  ansible.builtin.include_tasks: verify_certs.yml

- name: apiserver_certs_verify
  vars:
    certificate: "{{ apiserver_certificate }}"
    cert_hostname: "{{ certificate.hostname | default('api.'+cluster+'.'+base_domain) }}"
  when:
    - "'apiserver' in openshift_components"
    - apiserver_certificate is defined
  tags:
    - apiserver_certs
  ansible.builtin.include_tasks: verify_certs.yml
