---
- name: Ensure gitops directories exist
  vars:
    gitops_component: proxy
  ansible.builtin.include_tasks:
    file: create_gitops_dirs.yml

- name: Create asset files
  loop:
    - file: proxy.yaml
  ansible.builtin.template:
    src: proxy/{{ item.file }}.j2
    dest: "{{ openshift_gitops_dir }}/proxy/assets/{{ item.file }}"

- name: Generate kustomization file
  vars:
    gitops_component: proxy
  ansible.builtin.include_tasks:
    file: generate_kustomization.yml
