---
# Install bitnami sealed-secrets
- name: Add Application for bitnami sealed-secrets
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'sealed_secrets/application.yml.j2') | from_yaml }}"

- name: Download 'kubeseal' tool
  tags:
    - download
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ kubeseal_download_url }}"
    dest: /usr/local/bin
    mode: 493
    exclude:
      - LICENSE
      - README.md

- name: Include wait for CRDS
  vars:
    wait_for_crds:
      - sealedsecrets.bitnami.com
  ansible.builtin.include_tasks: wait_for_crds.yml

- name: Attempt to fetch certificate for cluster
  register: kubeseal_certificate_content
  until: kubeseal_certificate_content.rc == 0
  retries: 100
  delay: 10
  ansible.builtin.command: "{{ kubeseal_command }} --fetch-cert"

- name: Ensure directory exists for kubeseal certificates
  ansible.builtin.file:
    path: "{{ kubeseal_cert | dirname }}"
    state: directory
    recurse: true

- name: Write Kubeseal certificate to disk
  ansible.builtin.copy:
    dest: "{{ kubeseal_cert }}"
    content: "{{ kubeseal_certificate_content.stdout }}"
