---
# Install bitnami sealed-secrets
- name: Add Application for bitnami sealed-secrets
  k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'sealed_secrets/application.yml.j2') | from_yaml }}"

- name: Download 'kubeseal' tool
  unarchive:
    remote_src: true
    src: "{{ kubeseal_download_url }}"
    dest: /usr/local/bin
    mode: 0755
    exclude:
    - LICENSE
    - README.md
  tags:
  - download

- name: Include wait for CRDS
  include_tasks: wait_for_crds.yml
  vars:
    wait_for_crds:
    - sealedsecrets.bitnami.com

- name: Attempt to fetch certificate for cluster
  command: "{{ kubeseal_command }} --fetch-cert"
  register: kubeseal_certificate_content
  until: kubeseal_certificate_content.rc == 0
  retries: 100
  delay: 10

- name: Ensure directory exists for kubeseal certificates
  file:
    path: "{{ kubeseal_cert | dirname }}"
    state: directory
    recurse: yes

- name: Write Kubeseal certificate to disk
  copy:
    dest: "{{ kubeseal_cert }}"
    content: "{{ kubeseal_certificate_content.stdout }}"
