---
- name: Wait for CRD(s) to appear
  register: wait_for_crds_crds
  until:
    - wait_for_crds_crds.resources is defined
    - ( wait_for_crds_crds.resources | length ) > 0
  retries: 100
  loop: "{{ wait_for_crds }}"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ openshift_kubeconfig }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "{{ item }}"
