---
# Requirements:
# - Ensure access to the openshift cluster
# - Ensure user has cluster-admin permissions
# - Ensure an active 'oc login' session as another user than kubeadmin
# - Ensure at least one oauth provider is configured and working
# - Ensure that at least one oauth user/group has cluster-admin permissions

- name: Remove kubeadmin secret
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Remove kubeadmin secret
      k8s:
        kind: Secret
        name: kubeadmin
        namespace: kube-system
        state: absent
