---
- name: install or upgrade mirror quay
  tags:
    - install
  when:
    - mirror_registry_install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - install

- name: Sync content
  tags:
    - sync
  ansible.builtin.include_tasks:
    file: sync.yml
    apply:
      tags:
        - sync

- name: Process results
  tags:
    - process_results
  ansible.builtin.include_tasks:
    file: process_results.yml
    apply:
      tags:
        - process_results
