---
- name: Ensure output directory exists
  ansible.builtin.file:
    path: "{{ mirror_registry_download_dir }}/cluster-manifests"
    state: directory

- name: Run yamlmunger to parse icsp results
  ansible.builtin.script:
    cmd: yamlmunger.py {{ mirror_registry.directory }}/oc-mirror-workspace/results-*/*.yaml
  register: combined_output

- name: Store processed results for later usage
  ansible.builtin.copy:
    dest: "{{ mirror_registry_download_dir }}/cluster-manifests/cluster.yaml"
    content: "{{ combined_output.stdout }}"

- name: Run yamlmunger to parse release-signatures
  ansible.builtin.script:
    cmd: yamlmunger.py {{ mirror_registry.directory }}/oc-mirror-workspace/results-*/release-signatures/*json
  register: combined_output

- name: Store processed results for later usage
  ansible.builtin.copy:
    dest: "{{ mirror_registry_download_dir }}/cluster-manifests/release-signatures.yaml"
    content: "{{ combined_output.stdout }}"
