---
- name: Slurp API server cert
  register: apiserver_certificate_cert
  ansible.builtin.slurp:
    src: "{{ apiserver_certificate.certfile }}"

- name: Slurp API server key
  register: apiserver_certificate_key
  when:
    - not apiserver_certificate.keyfile_is_vaultencrypted | default(false)
  ansible.builtin.slurp:
    src: "{{ apiserver_certificate.keyfile }}"

- name: Update apiserver certs
  loop:
    - apiserver-certs.yml.j2
    - apiserver.yml.j2
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    validate_certs: false
    state: present
    definition: "{{ lookup('template', 'apiserver_certs/' + item) | from_yaml }}"
