---
- name: Deploy group-sync Objects
  loop:
    - group-sync-namespace.yml.j2
    - group-sync-operatorgroup.yml.j2
    - group-sync-subscription.yml.j2
    - azure-group-sync-secret.yml.j2
    - azure-cluster-admin-rolebinding.yml.j2
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'azure_groupsync/' + item) | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge

- name: Wait for operator CRDs to appear
  register: crds
  until: ( crds.resources | length ) > 0
  retries: 100
  loop:
    - groupsyncs.redhatcop.redhat.io
  kubernetes.core.k8s_info:
    kubeconfig: "{{ openshift_kubeconfig }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "{{ item }}"

- name: Deploy group-sync Objects
  loop:
    - group-sync.yml.j2
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'azure_groupsync/' + item) | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge
