---
# tasks file for create_iscsi_pvs
- name: debug
  debug:
    verbosity: 1
    msg: "{{ lookup('template', 'create_iscsi_pvs/iscsi-pv.yml.j2') }}"
  loop: "{{ iscsi_pvs }}" 

- name: List required storageclasses
  set_fact:
    iscsi_required_storageclass: "{{ iscsi_pvs | json_query('[*].storageclass') | unique }}"

- name: List storageclasse
  debug:
    verbosity: 1
    msg: "{{ item }}"
  loop: "{{ iscsi_required_storageclass }}"

- name: Break for deugging
  assert:
    that: false
  when: break is defined

- name: Create iSCSI storageclasses
  k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'create_iscsi_pvs/storageclass.yml.j2') | from_yaml }}"
    merge_type:
    - strategic-merge
    - merge
  loop: "{{ iscsi_required_storageclass }}" 


- name: Create iSCSI PVs
  k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'create_iscsi_pvs/iscsi-pv.yml.j2') | from_yaml }}"
    merge_type:
    - strategic-merge
    - merge
  loop: "{{ iscsi_pvs }}" 

