---
# tasks file for create_iscsi_pvs
- name: debug
  loop: "{{ iscsi_pvs }}"
  ansible.builtin.debug:
    verbosity: 1
    msg: "{{ lookup('template', 'create_iscsi_pvs/iscsi-pv.yml.j2') }}"

- name: List required storageclasses
  ansible.builtin.set_fact:
    iscsi_required_storageclass: "{{ iscsi_pvs | json_query('[*].storageclass') | unique }}"

- name: List storageclasse
  loop: "{{ iscsi_required_storageclass }}"
  ansible.builtin.debug:
    verbosity: 1
    msg: "{{ item }}"

- name: Break for deugging
  when: break is defined
  ansible.builtin.assert:
    that: false

- name: Create iSCSI storageclasses
  loop: "{{ iscsi_required_storageclass }}"

  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'create_iscsi_pvs/storageclass.yml.j2') | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge

- name: Create iSCSI PVs
  loop: "{{ iscsi_pvs }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'create_iscsi_pvs/iscsi-pv.yml.j2') | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge
