---
- name: Configure Custom Login Screen Templates
  loop:
    - name: login-template
      filename: login.html
    - name: providers-template
      filename: providers.html
    - name: error-template
      filename: errors.html
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    definition: "{{ lookup('template', 'custom_login/template-secret.yml.j2') | from_yaml }}"

- name: Configure Custom Login Screen
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    definition: "{{ lookup('template', 'custom_login/oauths-cluster.yml.j2') | from_yaml }}"
