---
- name: Add subscription for OpenShift GitOps Operator
  loop:
    - deploy_gitops/subscription.yml.j2
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item) | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge
