---
- name: Deploy Objects
  loop:
    - eventrouter-clusterrole.yml.j2
    - eventrouter-clusterrolebinding.yml.j2
    - eventrouter-configmap.yml.j2
    - eventrouter-sa.yml.j2
    - eventrouter-deployment.yml.j2
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'eventrouter/' + item) | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge
