---
- name: Read file
  set_fact:
    kubeconfig_content: "{{ lookup('file', openshift_kubeconfig ) | from_yaml }}"

- name: Extract cabundle
  set_fact:
    cabundlestring: "{{ kubeconfig_content.clusters[0]['cluster']['certificate-authority-data'] | default('') }}"
    cabundle: "{{ kubeconfig_content.clusters[0]['cluster']['certificate-authority-data'] | default('') | b64decode | regex_findall('(?ms)^-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----$', multiline=True) }}"

- name: Read extra certs
  set_fact:
    new_cacerts: "{{ lookup('file', custom_ca_file ) }}"

- name: Extract new cabundle
  set_fact:
    newcabundle: "{{ new_cacerts | regex_findall('(?ms)^-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----$', multiline=True) }}"

- name: Create combined cabundle
  set_fact:
    combined: "{{ cabundle | union(newcabundle) | unique }}"

- name: Update kubeconfig variable
  set_fact:
     newkubeconfig_content: "{{ kubeconfig_content | regex_replace(cabundlestring, combined | join('\n') | b64encode ) }}"

- name: Write new kubeconfig
  copy:
    dest: "{{ openshift_kubeconfig }}"
    content: "{{ newkubeconfig_content | to_nice_yaml(indent=2) }}"

- name: debug
  debug:
    msg: |
      Old cabundle had {{ cabundle | length }} entries
      Trying to add {{ newcabundle | length }} entries
      New cabundle has {{ combined | length }} entries
