---
- name: Move infra projects to infra nodes
  loop:
    - openshift-ingress.yaml.j2
    - cluster-config-move.yaml.j2
    - cluster-monitoring-move.yaml.j2
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'move_to_infra/' + item) | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge

- name: Get namespaces
  register: k8s_info_namespaces
  kubernetes.core.k8s_info:
    kubeconfig: "{{ openshift_kubeconfig }}"
    api_version: v1
    kind: Namespace

- name: Turn namespaces into list
  ansible.builtin.set_fact:
    ocp_namespaces: "{{ k8s_info_namespaces.resources | json_query('[*].metadata.name') }}"

- name: Set project node-selector to infra
  when: item in ocp_namespaces
  loop: "{{ move_to_infra_namespaces | default([]) }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'move_to_infra/project-nodeselector.yaml.j2') | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge

- name: Set default node-selector
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'move_to_infra/default-nodeselector.yaml.j2') | from_yaml }}"
    merge_type:
      - strategic-merge
      - merge
