---
- name: slurp CA and create
  loop: "{{ oauths }}"
  ansible.builtin.include_tasks: oauths_slurp_and_create_ca.yml

- name: Configure oauth bind passwords
  loop: "{{ oauths }}"
  when: item.type == 'LDAP'
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'oauth/oauths-bindpw.yml.j2') | from_yaml }}"

- name: Configure openid secrect
  loop: "{{ oauths }}"
  when: item.type == 'OpenID'
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'oauth/openid-connect-secret.yml.j2') | from_yaml }}"

- name: Configure Authentication
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'oauth/oauths.yml.j2') | from_yaml }}"
