---
- name: Slurp ca content
  register: oauths_ca_content
  ansible.builtin.slurp:
    src: "{{ item.cafile }}"

- name: Configure oauth trusted CAs
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'oauth/oauths-ca.yml.j2') | from_yaml }}"
