---
- name: Slurp
  register: router_cert_cert
  ansible.builtin.slurp:
    src: "{{ router.certfile }}"

- name: Slurp
  register: router_cert_key
  when:
    - not router.keyfile_is_vaultencrypted | default(false)
  ansible.builtin.slurp:
    src: "{{ router.keyfile }}"

- name: Update router secrets
  loop: "{{ routercerts_certificates }}"
  tags:
    - routers
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'routercerts/router-certs.yml.j2') | from_yaml }}"
