---
- name: Wait for namespace to appear
  register: namespaces
  until: ( namespaces.resources | length ) > 0
  loop:
    - openshift-ingress
  kubernetes.core.k8s_info:
    kubeconfig: "{{ openshift_kubeconfig }}"
    api_version: v1
    kind: Namespace
    name: "{{ item }}"

- name: Slurp certs and create secret
  loop: "{{ routercerts_certificates }}"
  loop_control:
    loop_var: router
  ansible.builtin.include_tasks: routercerts_slurp_and_create.yml
