---
- name: Configure self-provisioners
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'self-provisioners/self-provisioners.yml.j2') | from_yaml }}"
    force: true
