mirror_registry_operator_catalogs: |
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v{{ install_version_major_minor }}
    full: false
    packages:
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: odf-operator
      channels:
      - name: stable-{{ odf_storage_operator_channel | default(install_version_major_minor) }}
    - name: local-storage-operator
      channels:
      - name: stable
    - name: openshift-pipelines-operator-rh
      channels:
      - name: latest
    - name: serverless-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable
    - name: elasticsearch-operator
      channels:
      - name: stable
    - name: kiali-ossm
      channels:
      - name: stable
    - name: elasticsearch-operator
      channels:
      - name: stable
    - name: jaeger-product
      channels:
      - name: stable
    - name: servicemeshoperator
      channels:
      - name: stable
    - name: rhacs-operator
      channels:
      - name: stable
    - name: node-maintenance-operator
      channels:
      - name: stable
    - name: metallb-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable
    - name: loki-operator
      channels:
      - name: stable
    - name: compliance-operator
      channels:
      - name: stable
  - catalog: registry.redhat.io/redhat/community-operator-index:v{{ install_version_major_minor }}
    full: false
    packages:
    - name: group-sync-operator
      channels:
      - name: alpha
