---
# Cluster Monitoring
prometheus_retention: 2w
prometheus_storageclass: metrics
prometheus_storage_size: 150Gi

#User Workload Monitoring
monitoring_user_workload_enabled: true
prometheus_user_retention: 2w
prometheus_user_storageclass: metrics
prometheus_user_storage_size: 150Gi

# AlertManager
alertmanager_storageclass: odf-storagecluster-cephfs
alertmanager_storage_size: 5Gi
alertmanager_config:
  global:
    resolve_timeout: 5m
  route:
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: default
    routes:
      - match:
          alertname: Watchdog
        repeat_interval: 5m
        receiver: watchdog
  receivers:
    - name: default
      webhook_configs:
        - url: https://alerting.example.com/myorg/mytoken
          send_resolved: true
    - name: watchdog
