---
- name: Set base initramfs path
  ansible.builtin.set_fact:
    coreos_baseinitramfs_file: "{{ '/var/www/html/coreos/' + ( install_version ) + '/' + ( coreos_urls.initramfs.url | basename ) }}"

- name: Delete any old custom initramfs
  delegate_to: "{{ bastion_host }}"
  ansible.builtin.file:
    path: "{{ coreos_iso_output_dir }}/{{ inventory_hostname }}.initramfs"
    state: absent

- name: Create custom initramfs for host
  delegate_to: "{{ bastion_host }}"
  ansible.builtin.command: "{{ coreos_installer_command }} pxe customize {% for file in nmconnection_files.files %}--network-keyfile {{ file.path }} {% endfor %}
    --dest-device=/dev/{{ install_dev }} --dest-ignition /var/www/html/{{ inventory_hostname }}.ign --dest-karg-append console=tty0 --dest-karg-append console=ttyS0
    --dest-karg-append nomodeset -o {{ coreos_iso_output_dir }}/{{ inventory_hostname }}.initramfs {{ coreos_baseinitramfs_file }}"

- name: Set permissions to allow downloading initramfs
  delegate_to: "{{ bastion_host }}"
  ansible.builtin.file:
    path: "{{ coreos_iso_output_dir }}/{{ inventory_hostname }}.initramfs"
    mode: 420
