---
- name: set libvirt installer args
  when:
    - install_version is version('4.10', '<')
  ansible.builtin.set_fact:
    extra_install_args: --install kernel=http://{{ bastion_host }}/coreos/{{ install_version }}/{{ coreos_urls.kernel.url | basename }},initrd=http://{{ bastion_host
      }}/coreos/{{ install_version }}/{{ coreos_urls.initramfs.url | basename }},kernel_args_overwrite=yes,kernel_args="{{ coreos_installation_args }}" --wait

- name: set libvirt installer args
  when:
    - install_version is version('4.10', '>=')
  ansible.builtin.set_fact:
    extra_install_args: --install kernel=http://{{ bastion_host }}/coreos/{{ install_version }}/{{ coreos_urls.kernel.url | basename }},initrd=http://{{ bastion_host
      }}/{{ inventory_hostname}}.initramfs,kernel_args_overwrite=yes,kernel_args="{{ coreos_installation_args }}" --wait

- name: Get all VMS
  become: true
  delegate_to: "{{ virt_host }}"
  register: all_vms
  community.libvirt.virt:
    command: list_vms

- name: Bail if VM already present and force_vm_install=false
  ansible.builtin.assert:
    that: (inventory_hostname not in all_vms.list_vms) or (force_vm_install | default(False))

- name: Ensure virt-install is present
  become: true
  delegate_to: "{{ virt_host }}"
  ansible.builtin.dnf:
    name:
      - virt-install
      - cockpit
      - cockpit-machines
      - genisoimage
    state: present

- name: Ensure services are started
  loop:
    - firewalld
    - cockpit.socket
  become: true
  delegate_to: "{{ virt_host }}"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true

- name: Ensure firewall is opened up
  loop:
    - service: cockpit
  become: true
  delegate_to: "{{ virt_host }}"
  ansible.posix.firewalld:
    service: "{{ item.service | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    state: enabled
    permanent: true
    immediate: true

- name: Download base image
  become: true
  delegate_to: "{{ virt_host }}"
  when: base_image_url is defined
  tags:
    - download
  ansible.builtin.get_url:
    url: "{{ base_image_url }}"
    dest: /var/lib/libvirt/images/
    checksum: "{{ base_image_checksum | default(omit) }}"

- name: stop VM
  ignore_errors: true
  become: true
  delegate_to: "{{ virt_host }}"
  when: inventory_hostname in all_vms.list_vms
  community.libvirt.virt:
    name: "{{ inventory_hostname }}"
    state: destroyed

- name: undefine VM
  ignore_errors: true
  become: true
  delegate_to: "{{ virt_host }}"
  when: inventory_hostname in all_vms.list_vms
  community.libvirt.virt:
    name: "{{ inventory_hostname }}"
    command: undefine

- name: Create vm overlay
  become: true
  delegate_to: "{{ virt_host }}"
  when: base_image_url is defined
  ansible.builtin.command: qemu-img create -f qcow2 -b /var/lib/libvirt/images/{{ base_image_url | basename }} /var/lib/libvirt/images/{{ inventory_hostname }}.qcow2

- name: Create vm disk
  become: true
  delegate_to: "{{ virt_host }}"
  when: (image_size is defined) and (base_image_url is not defined)
  ansible.builtin.command: qemu-img create -f qcow2 /var/lib/libvirt/images/{{ inventory_hostname }}.qcow2 {{ image_size }}

- name: Create extra disks
  loop: "{{ extra_disks | default([]) }}"
  become: true
  delegate_to: "{{ virt_host }}"
  ansible.builtin.command: qemu-img create -f qcow2 /var/lib/libvirt/images/{{ inventory_hostname }}-{{ item.name }}.qcow2 {{ item.size }}

- name: Start virt-install
  become: true
  delegate_to: "{{ virt_host }}"
  async: 7200
  poll: 5
  ansible.builtin.command: virt-install -n {{ inventory_hostname }} --memory={{ virt_memory }} --vcpus={{ virt_vcpus }} --import --disk=/var/lib/libvirt/images/{{
    inventory_hostname }}.qcow2 {% for disk in extra_disks | default([]) %} --disk=/var/lib/libvirt/images/{{ inventory_hostname }}-{{ disk.name }}.qcow2 {% endfor
    %} {% for bridge in network_config %}{% if bridge.slaves is defined %}{% for slave in bridge.slaves %} --network bridge={{ slave.bridge }}{% if slave.mac is defined
    %},mac={{ slave.mac }}{% endif %} {% endfor %}{% else %} --network bridge={{ bridge.bridge }}{% if bridge.mac is defined %},mac={{ bridge.mac }}{% endif %}{%
    endif %}{% endfor %} --os-variant={{ virt_variant | default('rhel8.1') }} --noautoconsole --graphics=spice {{ extra_install_args | default('') }}

- name: Set domain to autostart or not
  become: true
  delegate_to: "{{ virt_host }}"
  community.libvirt.virt:
    name: "{{ inventory_hostname }}"
    autostart: "{{ virt_autostart | default(True) }}"
