---
- name: Include task preq_reqs
  ansible.builtin.include_tasks: pre_reqs.yml

- name: Include task register_kernel_args
  ansible.builtin.include_tasks: register_kernel_args.yml

- name: Include task create_ignitionfile
  ansible.builtin.include_tasks: create_ignitionfile.yml

- name: Include template NMConnections
  when:
    - install_version is version('4.10', '>=')
  ansible.builtin.include_tasks: template_nmconnection_files.yml

- name: Include create CoreOS initramfs
  when:
    - install_method in ['libvirt', 'grub']
    - install_version is version('4.10', '>=')
  ansible.builtin.include_tasks: create_coreos_installer_initramfs.yml

- name: Create custom CoreOS installer ISO
  when:
    - install_method in ['ilo', 'vmware', 'iso']
    - install_version is version('4.10', '>=')
  ansible.builtin.include_tasks: create_coreos_installer_iso.yml

- name: Include task create_iso
  when:
    - install_method in ['ilo', 'vmware']
    - install_version is version('4.10', '<')
  ansible.builtin.include_tasks: create_iso.yml

- name: Include task ilo
  when: install_method == 'ilo' and (ilo_boot_from_url | default(False)) == False
  ansible.builtin.include_tasks: ilo.yml

- name: Include task ilo_boot_from_url
  when: install_method == 'ilo' and (ilo_boot_from_url | default(False)) == True
  ansible.builtin.include_tasks: ilo_boot_from_url.yml

- name: Include task create_vmware_vm
  when: install_method == 'vmware'
  ansible.builtin.include_tasks: create_vmware_vm.yml

- name: Include task libvirt_install.yml
  when: install_method == 'libvirt'
  ansible.builtin.include_tasks: libvirt_install.yml

- name: Include task grub_install
  when: install_method == 'grub'
  ansible.builtin.include_tasks: grub_install.yml

- name: Wait for User Input
  when: install_method == 'iso'
  ansible.builtin.include_tasks: wait_for_user_input.yml

- name: Include task wait_for_cluster.yml
  ansible.builtin.include_tasks: wait_for_cluster.yml

- name: Include task label_nodes
  ansible.builtin.include_tasks: label_nodes.yml

- name: Include task machineconfigpools
  ansible.builtin.include_tasks: machineconfigpools.yml
