---
- name: Delete nmconnections directory for host
  delegate_to: "{{ bastion_host }}"
  ansible.builtin.file:
    path: "{{ openshift_nmconnections_dir }}/{{ inventory_hostname }}"
    state: absent

- name: Create nmconnections directory for host
  delegate_to: "{{ bastion_host }}"
  ansible.builtin.file:
    path: "{{ openshift_nmconnections_dir }}/{{ inventory_hostname }}"
    state: directory

- name: Template .nmconnection files for host
  delegate_to: "{{ bastion_host }}"
  ansible.builtin.command: "{{ nm_initrd_generator_command }} -c {{ openshift_nmconnections_dir }}/{{ inventory_hostname }} -- {{ coreos_installation_args }}"

- name: Find generated .nmconnection file
  delegate_to: "{{ bastion_host }}"
  register: nmconnection_files
  ansible.builtin.find:
    path: "{{ openshift_nmconnections_dir }}/{{ inventory_hostname }}"
    file_type: file
    patterns: "*.nmconnection"
