---
- name: Get DNS record
  delegate_to: "{{ bastion_host }}"
  run_once: true
  ansible.builtin.set_fact:
    dns_ip: "{{ lookup('dig', item) }}"

- name: Abort if DNS entry can not be found
  run_once: true
  delegate_to: "{{ bastion_host }}"
  ansible.builtin.assert:
    success_msg: |
      {{ item }} resolves to: {{ dns_ip }}
    fail_msg: |
      {% if dns_ip == 'NXDOMAIN' %}
      Could not resolve {{ item }}
      {% else %}
      {{ item }} resolves to: {{ dns_ip }}
      {% endif %}
    that:
      - dns_ip != 'NXDOMAIN'
